version: '3.3'

services:
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=banco
      - MYSQL_USER=banco
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
